'use strict';
const crypto=require('crypto'),repo=require('./repositorio'),geo=require('../geo/geotepic');
const ORDEN=['distancia','territorio','clima','calendario','horario','demanda','extraordinario','restriccion'];
function hav(a,b,c,d){const r=x=>x*Math.PI/180,R=6371,x=r(c-a),y=r(d-b),z=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function fechaTepic(momento){const partes=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(momento));const p=Object.fromEntries(partes.map(x=>[x.type,x.value]));return`${p.year}-${p.month}-${p.day}`}
function horaTepic(momento){return new Intl.DateTimeFormat('en-GB',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(momento))}
function coincide(r,c){const x=r.condicion||{};if(r.categoria==='distancia'){const h=x.hasta_km==null?Infinity:Number(x.hasta_km);return c.distanciaKm>=Number(x.desde_km||0)&&(h===Infinity||c.distanciaKm<h)}if(['territorio','restriccion'].includes(r.categoria))return !x.cuadrante_id||c.zonas.some(z=>z.id===Number(x.cuadrante_id));if(r.categoria==='calendario'&&x.fecha)return x.fecha===fechaTepic(c.momento);if(r.categoria==='horario'){const ahora=horaTepic(c.momento),desde=x.hora_desde,hasta=x.hora_hasta;return desde<hasta?ahora>=desde&&ahora<hasta:ahora>=desde||ahora<hasta}return c.condiciones.some(v=>v.tipo===r.categoria&&(!x.nivel||v.nivel===x.nivel)&&(!v.cuadrante_id||c.zonas.some(z=>z.id===v.cuadrante_id)))}
function seleccionar(rs,c){const out=[];for(const cat of ORDEN){const g=rs.filter(r=>r.activa&&r.categoria===cat&&coincide(r,c)).sort((a,b)=>a.prioridad-b.prioridad||a.id-b.id),exc=g.filter(r=>!r.acumulable);out.push(...g.filter(r=>r.acumulable));if(exc.length)out.push(exc[0])}return out}
function aplicar(t,r){if(r.tipo_ajuste==='fijo')return t+Number(r.valor);if(r.tipo_ajuste==='porcentaje')return t*(1+Number(r.valor)/100);if(r.tipo_ajuste==='multiplicador')return t*Number(r.valor);return t}
function cotizarEntrega({tenantId,colonia,origenLat,origenLon,momento=new Date(),condicionesSimuladas=null,persistir=true,vigenciaMin=10,usarBorrador=false}={}){
 const p=repo.obtenerPolitica(),version=usarBorrador?p.version_borrador:p.version_publicada;if(!version)return{configurada:false};const v=usarBorrador?p:repo.obtenerVersionPolitica(version);if(!v)return{configurada:false,motivo:'version_no_disponible'};
 const la=Number(origenLat),lo=Number(origenLon);if(!Number.isFinite(la)||!Number.isFinite(lo))throw Error('La ubicación de origen no es válida');const u=geo.obtenerZonaDeColonia(colonia),km=Math.round(hav(la,lo,u.ubicacion.lat,u.ubicacion.lng)*100)/100;
 let cs=repo.condicionesVigentes(momento);if(Array.isArray(condicionesSimuladas))cs=condicionesSimuladas.map((x,i)=>({id:`sim-${i}`,...x}));const ctx={distanciaKm:km,zonas:u.zonas,condiciones:cs,momento:new Date(momento).toISOString()},aps=seleccionar(repo.listarReglas(version),ctx);
 const base=aps.filter(r=>r.categoria==='distancia');if(base.length!==1)return{configurada:false,motivo:base.length?'distancia_ambigua':'sin_regla_distancia'};const bloqueo=aps.find(r=>r.tipo_ajuste==='bloqueo');if(bloqueo)return{configurada:true,disponible:false,motivo:bloqueo.nombre,tenantId,colonia:u.colonia,distanciaKm:km,zonas:u.zonas};
 let total=0;const desglose=[];for(const r of aps){if(r.tipo_ajuste==='bloqueo')continue;const antes=total;total=aplicar(total,r);desglose.push({reglaId:r.id,nombre:r.nombre,categoria:r.categoria,tipo:r.tipo_ajuste,valor:r.valor,antes,despues:total,importe:total-antes})}if(v.tarifa_minima!=null)total=Math.max(total,Number(v.tarifa_minima));total=Math.ceil((total-Number.EPSILON)/(Number(v.redondeo)||1))*(Number(v.redondeo)||1);const limitada=v.alerta_maxima!=null&&total>Number(v.alerta_maxima);if(limitada){const antes=total;total=Number(v.alerta_maxima);desglose.push({reglaId:null,nombre:'Tarifa máxima',categoria:'limite',tipo:'maximo',valor:total,antes,despues:total,importe:total-antes})}
 const id=`cot_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`,exp=new Date(Date.now()+Math.max(1,Number(vigenciaMin)||10)*60000),res={configurada:true,disponible:true,cotizacionId:id,tenantId,empresaId:p.empresa_id,politicaId:p.id,politica:'Tarifa global Tepic',perfilVersion:version,politicaVersion:version,esBorrador:usarBorrador,moneda:v.moneda,tarifa:total,tarifaMaximaAplicada:limitada,colonia:u.colonia,distanciaKm:km,zonas:u.zonas,condiciones:cs.map(x=>({tipo:x.tipo,nivel:x.nivel,nombre:x.nombre})),desglose,expiraEn:exp.toISOString()};
 if(persistir)repo.guardarCotizacion({id,tenant_id:String(tenantId),empresa_id:p.empresa_id,politica_id:p.id,politica_version:version,ambito:repo.AMBITO,colonia:u.colonia,origen_lat:la,origen_lon:lo,destino_lat:u.ubicacion.lat,destino_lon:u.ubicacion.lng,distancia_km:km,tarifa:total,moneda:v.moneda,desglose_json:JSON.stringify(desglose),contexto_json:JSON.stringify(ctx),supera_alerta_maxima:limitada?1:0,expira_en:exp.toISOString()});return res;
}
module.exports={cotizarEntrega};
