'use strict';
const { getAdminDB } = require('../db/admin');
const AMBITO = 'tepic-nayarit';
let inicializado = false;
function init() {
  if (inicializado) return;
  const d=getAdminDB(); d.exec(`
  CREATE TABLE IF NOT EXISTS logistica_empresas(id INTEGER PRIMARY KEY,nombre TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,activa INTEGER DEFAULT 1,created_at TEXT DEFAULT(datetime('now','localtime')));
  CREATE TABLE IF NOT EXISTS logistica_politicas_globales(id INTEGER PRIMARY KEY,empresa_id INTEGER NOT NULL,ambito TEXT UNIQUE NOT NULL,nombre TEXT NOT NULL,moneda TEXT DEFAULT 'MXN',redondeo REAL DEFAULT 5,tarifa_minima REAL,alerta_maxima REAL,version_borrador INTEGER DEFAULT 1,version_publicada INTEGER,activa INTEGER DEFAULT 1,created_at TEXT DEFAULT(datetime('now','localtime')),updated_at TEXT DEFAULT(datetime('now','localtime')));
  CREATE TABLE IF NOT EXISTS logistica_reglas_globales(id INTEGER PRIMARY KEY,politica_id INTEGER NOT NULL,version INTEGER NOT NULL,nombre TEXT NOT NULL,categoria TEXT NOT NULL,condicion_json TEXT DEFAULT '{}',tipo_ajuste TEXT NOT NULL,valor REAL DEFAULT 0,prioridad INTEGER DEFAULT 100,acumulable INTEGER DEFAULT 1,activa INTEGER DEFAULT 1,created_at TEXT DEFAULT(datetime('now','localtime')),updated_at TEXT DEFAULT(datetime('now','localtime')));
  CREATE TABLE IF NOT EXISTS logistica_versiones_globales(politica_id INTEGER NOT NULL,version INTEGER NOT NULL,moneda TEXT NOT NULL,redondeo REAL NOT NULL,tarifa_minima REAL,alerta_maxima REAL,publicada_en TEXT DEFAULT(datetime('now','localtime')),PRIMARY KEY(politica_id,version));
  CREATE TABLE IF NOT EXISTS logistica_condiciones_globales(id INTEGER PRIMARY KEY,empresa_id INTEGER NOT NULL,ambito TEXT NOT NULL,tipo TEXT NOT NULL,nivel TEXT NOT NULL,nombre TEXT NOT NULL,cuadrante_id INTEGER,inicio TEXT NOT NULL,fin TEXT NOT NULL,activa INTEGER DEFAULT 1,origen TEXT DEFAULT 'manual',created_by TEXT,created_at TEXT DEFAULT(datetime('now','localtime')));
  CREATE TABLE IF NOT EXISTS logistica_cotizaciones_globales(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,empresa_id INTEGER NOT NULL,politica_id INTEGER NOT NULL,politica_version INTEGER NOT NULL,ambito TEXT NOT NULL,colonia TEXT NOT NULL,origen_lat REAL NOT NULL,origen_lon REAL NOT NULL,destino_lat REAL NOT NULL,destino_lon REAL NOT NULL,distancia_km REAL NOT NULL,tarifa REAL NOT NULL,moneda TEXT DEFAULT 'MXN',desglose_json TEXT NOT NULL,contexto_json TEXT NOT NULL,supera_alerta_maxima INTEGER DEFAULT 0,estado TEXT DEFAULT 'cotizada',expira_en TEXT NOT NULL,pedido_id INTEGER,created_at TEXT DEFAULT(datetime('now','localtime')));
  CREATE INDEX IF NOT EXISTS idx_log_reglas_global ON logistica_reglas_globales(politica_id,version,categoria,prioridad);
  CREATE INDEX IF NOT EXISTS idx_log_cot_global ON logistica_cotizaciones_globales(tenant_id,created_at);`);
  d.prepare("INSERT OR IGNORE INTO logistica_empresas(id,nombre,slug) VALUES(1,'Operación logística Rajem','operacion-rajem')").run();
  d.prepare("INSERT OR IGNORE INTO logistica_politicas_globales(empresa_id,ambito,nombre) VALUES(1,?,'Tarifa global Tepic')").run(AMBITO);
  d.prepare('INSERT OR IGNORE INTO schema_migrations(version) VALUES(?)').run('2026-08-21-logistica-global-tepic-v2'); inicializado=true;
}
function db(){init();return getAdminDB();} function json(v,f={}){try{return JSON.parse(v||'')}catch{return f}}
function listarEmpresas(){return db().prepare('SELECT * FROM logistica_empresas').all()}
function obtenerPolitica(){return db().prepare('SELECT * FROM logistica_politicas_globales WHERE ambito=? AND activa=1').get(AMBITO)}
function obtenerVersionPolitica(v){const p=obtenerPolitica();return db().prepare('SELECT * FROM logistica_versiones_globales WHERE politica_id=? AND version=?').get(p.id,Number(v))}
function actualizarPolitica(x={}){const p=obtenerPolitica(),r=Number(x.redondeo??p.redondeo),m=x.tarifa_minima===''?null:(x.tarifa_minima??p.tarifa_minima),entradaMax=x.tarifa_maxima!==undefined?x.tarifa_maxima:x.alerta_maxima,a=entradaMax===''?null:(entradaMax??p.alerta_maxima);if(!Number.isFinite(r)||r<=0)throw Error('El redondeo debe ser mayor que cero');if(m!=null&&Number(m)<0)throw Error('Tarifa mínima inválida');if(a!=null&&Number(a)<0)throw Error('Tarifa máxima inválida');if(m!=null&&a!=null&&Number(m)>Number(a))throw Error('La tarifa mínima no puede superar la tarifa máxima');db().prepare("UPDATE logistica_politicas_globales SET redondeo=?,tarifa_minima=?,alerta_maxima=?,updated_at=datetime('now','localtime') WHERE id=?").run(r,m==null?null:Number(m),a==null?null:Number(a),p.id);return obtenerPolitica()}
const cats=new Set(['distancia','territorio','clima','calendario','horario','demanda','extraordinario','restriccion']);
function validar(x){if(!cats.has(x.categoria))throw Error('Categoría inválida');const permitidos=x.categoria==='distancia'?['fijo']:x.categoria==='restriccion'?['bloqueo']:['fijo','porcentaje','multiplicador'];if(!permitidos.includes(x.tipo_ajuste))throw Error('Ese ajuste no está permitido para la categoría');const c=typeof x.condicion==='string'?json(x.condicion,null):(x.condicion||{}),v=Number(x.valor||0);if(!c||typeof c!=='object'||Array.isArray(c)||!Number.isFinite(v)||v<0)throw Error('Regla inválida');if(x.tipo_ajuste==='multiplicador'&&v<=0)throw Error('Multiplicador inválido');if(x.categoria==='distancia'){const de=Number(c.desde_km??0),hasta=c.hasta_km==null?Infinity:Number(c.hasta_km);if(de<0||hasta<=de)throw Error('Rango de distancia inválido')}if(x.categoria==='territorio'&&!Number(c.cuadrante_id))throw Error('Selecciona un cuadrante');if(['clima','calendario'].includes(x.categoria)&&!String(c.nivel||'').trim())c.nivel=String(x.nombre||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');if(['clima','calendario'].includes(x.categoria)&&!c.nivel)throw Error('El nombre no permite generar una clave válida');if(x.categoria==='calendario'&&!/^\d{4}-\d{2}-\d{2}$/.test(String(c.fecha||'')))throw Error('Selecciona la fecha del día festivo');if(x.categoria==='horario'){const formato=/^(?:[01]\d|2[0-3]):[0-5]\d$/;if(!formato.test(String(c.hora_desde||''))||!formato.test(String(c.hora_hasta||'')))throw Error('Selecciona horas de inicio y fin válidas');if(c.hora_desde===c.hora_hasta)throw Error('La hora de inicio y fin deben ser diferentes')}return{c,v}}
function listarReglas(v){const p=obtenerPolitica();return db().prepare('SELECT * FROM logistica_reglas_globales WHERE politica_id=? AND version=? ORDER BY categoria,prioridad,id').all(p.id,Number(v||p.version_borrador)).map(r=>({...r,condicion:json(r.condicion_json)}))}
function guardarRegla(x={},id=null){const p=obtenerPolitica(),{c,v}=validar(x),n=String(x.nombre||'').trim();if(!n)throw Error('Nombre obligatorio');if(id){const a=db().prepare('SELECT id FROM logistica_reglas_globales WHERE id=? AND politica_id=? AND version=?').get(Number(id),p.id,p.version_borrador);if(!a)throw Error('Regla de borrador no encontrada');db().prepare("UPDATE logistica_reglas_globales SET nombre=?,categoria=?,condicion_json=?,tipo_ajuste=?,valor=?,prioridad=?,acumulable=?,activa=?,updated_at=datetime('now','localtime') WHERE id=?").run(n,x.categoria,JSON.stringify(c),x.tipo_ajuste,v,Number(x.prioridad??100),x.acumulable===false?0:1,x.activa===false?0:1,Number(id));return Number(id)}return db().prepare('INSERT INTO logistica_reglas_globales(politica_id,version,nombre,categoria,condicion_json,tipo_ajuste,valor,prioridad,acumulable,activa) VALUES(?,?,?,?,?,?,?,?,?,?)').run(p.id,p.version_borrador,n,x.categoria,JSON.stringify(c),x.tipo_ajuste,v,Number(x.prioridad??100),x.acumulable===false?0:1,x.activa===false?0:1).lastInsertRowid}
function eliminarRegla(id){const p=obtenerPolitica();return db().prepare('DELETE FROM logistica_reglas_globales WHERE id=? AND politica_id=? AND version=?').run(Number(id),p.id,p.version_borrador).changes>0}
function validarBandas(rs){const b=rs.filter(r=>r.categoria==='distancia').map(r=>[Number(r.condicion.desde_km??0),r.condicion.hasta_km==null?Infinity:Number(r.condicion.hasta_km)]).sort((a,b)=>a[0]-b[0]);if(!b.length||b[0][0]!==0)throw Error('Las tarifas por distancia deben comenzar en 0 km');for(let i=1;i<b.length;i++)if(b[i][0]!==b[i-1][1])throw Error('Las tarifas por distancia no pueden tener huecos ni traslapes')}
function publicarPolitica(){const p=obtenerPolitica(),rs=listarReglas(p.version_borrador).filter(r=>r.activa);validarBandas(rs);const ins=db().prepare('INSERT INTO logistica_reglas_globales(politica_id,version,nombre,categoria,condicion_json,tipo_ajuste,valor,prioridad,acumulable,activa) VALUES(?,?,?,?,?,?,?,?,?,?)');db().transaction(()=>{db().prepare('INSERT INTO logistica_versiones_globales(politica_id,version,moneda,redondeo,tarifa_minima,alerta_maxima) VALUES(?,?,?,?,?,?)').run(p.id,p.version_borrador,p.moneda,p.redondeo,p.tarifa_minima,p.alerta_maxima);db().prepare("UPDATE logistica_politicas_globales SET version_publicada=?,version_borrador=?,updated_at=datetime('now','localtime') WHERE id=?").run(p.version_borrador,p.version_borrador+1,p.id);for(const r of rs)ins.run(p.id,p.version_borrador+1,r.nombre,r.categoria,r.condicion_json,r.tipo_ajuste,r.valor,r.prioridad,r.acumulable,r.activa)})();return obtenerPolitica()}
function guardarCondicion(x={},u='superadmin'){const ini=new Date(x.inicio),fin=new Date(x.fin);if(!['clima','calendario','demanda','extraordinario'].includes(x.tipo)||!x.nivel||!x.nombre||isNaN(ini)||isNaN(fin)||fin<=ini)throw Error('Condición y vigencia inválidas');return db().prepare('INSERT INTO logistica_condiciones_globales(empresa_id,ambito,tipo,nivel,nombre,cuadrante_id,inicio,fin,activa,origen,created_by) VALUES(1,?,?,?,?,?,?,?,?,?,?)').run(AMBITO,x.tipo,x.nivel,x.nombre,x.cuadrante_id?Number(x.cuadrante_id):null,ini.toISOString(),fin.toISOString(),x.activa===false?0:1,String(x.origen||'manual'),u).lastInsertRowid}
function listarCondiciones(){return db().prepare('SELECT c.*,q.nombre cuadrante_nombre FROM logistica_condiciones_globales c LEFT JOIN geo_tepic_cuadrantes q ON q.id=c.cuadrante_id WHERE c.ambito=? ORDER BY c.inicio DESC').all(AMBITO)}
function desactivarCondicion(id){return db().prepare('UPDATE logistica_condiciones_globales SET activa=0 WHERE id=? AND ambito=?').run(Number(id),AMBITO).changes>0}
function alternarFiltroClima(nivel,usuario='superadmin'){const p=obtenerPolitica(),clave=String(nivel||'').trim();if(!p.version_publicada)throw Error('Primero publica la política');const regla=listarReglas(p.version_publicada).find(r=>r.activa&&r.categoria==='clima'&&r.condicion.nivel===clave);if(!regla)throw Error('Filtro climático publicado no encontrado');const actual=db().prepare("SELECT * FROM logistica_condiciones_globales WHERE ambito=? AND tipo='clima' AND activa=1 ORDER BY id DESC LIMIT 1").get(AMBITO);let activada=true;db().transaction(()=>{db().prepare("UPDATE logistica_condiciones_globales SET activa=0 WHERE ambito=? AND tipo='clima' AND activa=1").run(AMBITO);if(actual?.nivel===clave){activada=false;return}db().prepare("INSERT INTO logistica_condiciones_globales(empresa_id,ambito,tipo,nivel,nombre,inicio,fin,activa,origen,created_by) VALUES(1,?,'clima',?,?,?, ?,1,'manual',?)").run(AMBITO,clave,regla.nombre,new Date().toISOString(),'9999-12-31T23:59:59.999Z',usuario)})();return{activa:activada,nivel:activada?clave:null}}
function condicionesVigentes(m=new Date()){const i=new Date(m).toISOString();return db().prepare('SELECT * FROM logistica_condiciones_globales WHERE ambito=? AND activa=1 AND inicio<=? AND fin>=? ORDER BY id').all(AMBITO,i,i)}
function guardarCotizacion(c){db().prepare('INSERT INTO logistica_cotizaciones_globales(id,tenant_id,empresa_id,politica_id,politica_version,ambito,colonia,origen_lat,origen_lon,destino_lat,destino_lon,distancia_km,tarifa,moneda,desglose_json,contexto_json,supera_alerta_maxima,expira_en) VALUES(@id,@tenant_id,@empresa_id,@politica_id,@politica_version,@ambito,@colonia,@origen_lat,@origen_lon,@destino_lat,@destino_lon,@distancia_km,@tarifa,@moneda,@desglose_json,@contexto_json,@supera_alerta_maxima,@expira_en)').run(c)}
function listarCotizaciones(l=100){return db().prepare('SELECT * FROM logistica_cotizaciones_globales ORDER BY created_at DESC LIMIT ?').all(Math.min(500,Math.max(1,Number(l)||100))).map(c=>({...c,desglose:json(c.desglose_json,[]),contexto:json(c.contexto_json)}))}
function vincularCotizacion(id,p){return !!(id&&p&&db().prepare("UPDATE logistica_cotizaciones_globales SET pedido_id=?,estado='aceptada' WHERE id=? AND estado='cotizada'").run(Number(p),String(id)).changes)}
module.exports={AMBITO,inicializarLogistica:init,listarEmpresas,obtenerPolitica,obtenerVersionPolitica,actualizarPolitica,listarReglas,guardarRegla,eliminarRegla,publicarPolitica,guardarCondicion,listarCondiciones,desactivarCondicion,alternarFiltroClima,condicionesVigentes,guardarCotizacion,listarCotizaciones,vincularCotizacion,parseJson:json};
